<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-27 at 03:32:08.
 */
class AccountTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Account
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Account;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
