<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-25 at 14:27:01.
 */
require_once '../model/Client.php';
class ClientTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Client
     */
    protected $client;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->client = new Client("Michele",890);
        $this->client->setAccount(2);
        $this->client->setQualification(6.7);
        $this->client->setMedia("files-media");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Client::registerUser
     * @todo   Implement testRegisterUser().
     */
    public function testa_metodo_register_user() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(6, $this->client->registerUser());
    }

    /**
     * @covers Client::requestRelationship
     * @todo   Implement testRequestRelationship().
     */
    public function testa_metodo_request_relationship() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(NULL, $this->client->requestRelationship(3));
    }

}
