<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-25 at 14:27:01.
 */
require_once '..\model\Client.php';
class ClientTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Client
     */
    protected $client;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->client = new Client("Cicero");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Client::registerUser
     * @todo   Implement testRegisterUser().
     */
    public function testRegisterUser() {
        // Remove the following lines when you implement this test.
        $this->assertEquals("Cicero", $this->client->registerUser());
    }

    /**
     * @covers Client::requestRelationship
     * @todo   Implement testRequestRelationship().
     */
    public function testRequestRelationship() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(NULL, $this->client->requestRelationship());
    }

}
