<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-27 at 03:35:25.
 */
require_once '../model/Connection.php';
class ConnectionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Connection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Connection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
function testa_conexao_com_banco_de_dados(){
        $this->conn = new PDO("mysql:host=localhost;dbname=findferdb","root", "ffapp2017ffapp");
        $this->assertEquals($this->conn,  $this->object->connect());
    }
    function testa_methodo_insert(){
        $this->object->setEntity('media_type');
        $this->object->setRowData('name_type',"JPG");
        $this->assertEquals("INSERT INTO media_type (name_type)VALUES ('JPG')",$this->object->insert() );
    }
}
