<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-01 at 19:20:54.
 */
class CriteriaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Criteria
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Criteria;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Criteria::add
     * @todo   Implement testAdd().
     */
    public function testAdd() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Criteria::dump
     * @todo   Implement testDump().
     */
    public function testDump() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Criteria::setProperty
     * @todo   Implement testSetProperty().
     */
    public function testSetProperty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Criteria::getProperty
     * @todo   Implement testGetProperty().
     */
    public function testGetProperty() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
