<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-01 at 19:19:32.
 */
class FilterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Filter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Filter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Filter::dump
     * @todo   Implement testDump().
     */
    public function testDump() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
