<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-27 at 02:03:29.
 */
require_once '../model/Marketer.php';
class MarketerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Marketer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Marketer();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Marketer::registerUser
     * @todo   Implement testRegisterUser().
     */


    function testa_se_retorna_nome_feirante(){
        $this->object->setName("Cicero");
        $this->assertEquals('Cicero',  $this->object->getName());
    }
    function testa_se_retorna_um_feirante(){
        $this->assertEquals('fisasdadaee@gmail.com',  $this->object->loadMaketer('catiane','1234')->getEmail());
    }
    function testa_object_null(){
        $this->assertEquals('Opa! Nenhum usuário enscotrado.',  $this->object->loadMaketer('catiane','1tgg')->getName());
    }
    function testa_se_as_querys_sao_criadas_corretamente(){
        $params = "user_name = michelle AND password = 6564337";
        $this->assertEquals("SELECT * FROM user WHERE user_name = michelle AND password = 6564337 AND id_conta > 1",
        $this->object->getQuery('*',$params));
    }

}
