<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-27 at 02:03:29.
 */
class MarketerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Marketer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Marketer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Marketer::registerUser
     * @todo   Implement testRegisterUser().
     */
    public function testRegisterUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Marketer::requestRelationship
     * @todo   Implement testRequestRelationship().
     */
    public function testRequestRelationship() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
