<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-27 at 03:05:28.
 */
require_once '../model/Media.php';
class MediaTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Media
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Media("banana.jpg","var/www/html/findfer/img/product/");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Media::toString
     * @todo   Implement testToString().
     */
    public function testToString() {
        // Remove the following lines when you implement this test.
        $this->assertEquals("var/www/html/findfer/img/product/banana.jpg",  $this->object->toString());
    }

}
