<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-27 at 03:33:23.
 */
require_once '../model/MediaType.php';
class MediaTypeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MediaType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MediaType('MPEG');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    function testa_funcao_to_string(){
        $this->assertEquals('MPEG', $this->object->toString());
    }

}
