<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-27 at 03:33:35.
 */
class PerimeterTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Perimeter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Perimeter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
