<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-27 at 02:03:49.
 */
class ProductTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Product
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Product;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
