<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-31 at 21:43:58.
 */
require_once '../control/LoadPosters.php';

class LoadPostersTest extends PHPUnit_Framework_TestCase {

    /**
     * @var LoadPosters
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LoadPosters();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers LoadPosters::selectPosts
     * @todo   Implement testSelectPosts().
     */
    public function testSelectPosts() {
        // Remove the following lines when you implement this test.
        $this->assertEquals(NULL,$this->object->selectPosts());
    }

}
