<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-14 at 15:07:18.
 */
require_once '../control/LoadUser.php';
class LoadUserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var LoadUser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new LoadUser('catiane','1234');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    function test(){
        $this->assertEquals('',$this->object->defineUser());
        
    }

}
